version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=internal_menu_selection
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    networks:
      - 'internal'
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=internal_menu_selection
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: > 
      sh -c "python manage.py migrate && python manage.py runscript add_permissions && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - 'internal'

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge