# Generated by Django 4.1.3 on 2022-11-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_fooditem_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="food_item",
        ),
        migrations.CreateModel(
            name="MenuFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.fooditem",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.menu",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="food_item",
            field=models.ManyToManyField(
                through="restaurant.MenuFoodItem", to="restaurant.fooditem"
            ),
        ),
    ]
