# Generated by Django 4.1.3 on 2022-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "User Roles",
                "permissions": [("list_role", "Can list role")],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="User Roles_name_2d27c2_idx"),
        ),
    ]
